/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { OptionItem } from "./components/zen-dropdown-simple/zen-dropdown-simple";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ZenDropdownSimple {
        "options": Array<OptionItem>;
        "value": string;
    }
    interface ZenSimple {
        "name": string;
        "opened": boolean;
        "value": string;
    }
    interface ZenSimpleNonShadow {
        "name": string;
        "opened": boolean;
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLZenDropdownSimpleElement extends Components.ZenDropdownSimple, HTMLStencilElement {
    }
    var HTMLZenDropdownSimpleElement: {
        prototype: HTMLZenDropdownSimpleElement;
        new (): HTMLZenDropdownSimpleElement;
    };
    interface HTMLZenSimpleElement extends Components.ZenSimple, HTMLStencilElement {
    }
    var HTMLZenSimpleElement: {
        prototype: HTMLZenSimpleElement;
        new (): HTMLZenSimpleElement;
    };
    interface HTMLZenSimpleNonShadowElement extends Components.ZenSimpleNonShadow, HTMLStencilElement {
    }
    var HTMLZenSimpleNonShadowElement: {
        prototype: HTMLZenSimpleNonShadowElement;
        new (): HTMLZenSimpleNonShadowElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "zen-dropdown-simple": HTMLZenDropdownSimpleElement;
        "zen-simple": HTMLZenSimpleElement;
        "zen-simple-non-shadow": HTMLZenSimpleNonShadowElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ZenDropdownSimple {
        "options"?: Array<OptionItem>;
        "value"?: string;
    }
    interface ZenSimple {
        "name"?: string;
        "opened"?: boolean;
        "value"?: string;
    }
    interface ZenSimpleNonShadow {
        "name"?: string;
        "opened"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "zen-dropdown-simple": ZenDropdownSimple;
        "zen-simple": ZenSimple;
        "zen-simple-non-shadow": ZenSimpleNonShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "zen-dropdown-simple": LocalJSX.ZenDropdownSimple & JSXBase.HTMLAttributes<HTMLZenDropdownSimpleElement>;
            "zen-simple": LocalJSX.ZenSimple & JSXBase.HTMLAttributes<HTMLZenSimpleElement>;
            "zen-simple-non-shadow": LocalJSX.ZenSimpleNonShadow & JSXBase.HTMLAttributes<HTMLZenSimpleNonShadowElement>;
        }
    }
}
